### ISSUE TITLE
"unlucky" div-ids

### ISSUE THREAD

**Issue by useltmann** [TEIC/Stylesheets#153]
the generated `div`-ids which are used to jump to a paragraph from the table of contents are a bit unlucky since _jquery_ cannot handle element ids with dots in it. it would be great, if this element separator could be something else.

**Comment by peterstadler** [comment]
Sorry, can you give an example where you see these ids?
Second, wouldn't escaping the dots in JQuery with `\\.` help? See http://stackoverflow.com/questions/605630/how-to-select-html-nodes-by-id-with-jquery-when-the-id-contains-a-dot

**Comment by useltmann** [comment]
Hi, thanks for the quick reply.
You can see these ids in the  [Stylesheet-Tests' expected results](Stylesheets/Test/expected-results/test.html).

The escaping method is a good idea, i will recommend that.

**Comment by martindholmes** [comment]
I appreciate that lots of people use JQuery, but it's not a standard. If JQuery has problems with ids which are valid identifiers, that seems like a bug in JQuery, surely?

**Comment by hcayless** [comment]
It's not a bug. The problem is that JQuery allows you to resolve elements via CSS-like selectors, and the '.' normally signals a class, so JQuery is going to think `$("#foo.bar")` means "find the element with `@id` foo and `@class` bar. The best thing to do is to escape them as @peterstadler recommends. It doesn't like commas either. In HTML5, pretty much anything except spaces can be an id attribute value, iirc.

**Comment by peterstadler** [comment]
ok to close the ticket?

**Comment by hcayless** [comment]
Yes. :-)

**Comment by martindholmes** [comment]
@hcayless: Would these periods cause a problem for document.querySelect() and document.querySelectAll()?

**Comment by hcayless** [comment]
@martindholmes Quite likely. You'd have to escape them in the same way.
