### ISSUE TITLE
Commit made to wrong branch

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#196]
This commit by @emchateau:

https://github.com/TEIC/Stylesheets/commit/66dd1e6fef4a16b33d45b20e530529ed1730d6f4

was made not to the dev branch but to the main branch; it seems to have broken the build too, although I don't see why. It also seems to be an incomplete fix. This is the original block, as it still appears in the dev branch:

~~~~~
<xsl:choose>
		  <xsl:when test="$depth=0">chapter</xsl:when>
		  <xsl:when test="$depth=1">section</xsl:when>
		  <xsl:when test="$depth=2">subsection</xsl:when>
		  <xsl:when test="$depth=4">subsunsection</xsl:when>
		  <xsl:when test="$depth=4">paragraph</xsl:when>
		  <xsl:when test="$depth=5">subparagraph</xsl:when>
		  <xsl:otherwise>section</xsl:otherwise>
		</xsl:choose>
~~~~~

The commit amends the obvious typo "subsunsection" to "subsubsection", but actually as far as I can see that line could never be executed because its test is identical to the preceding test. I think line 196 should be:

~~~~~
		  <xsl:when test="$depth=3">subsubsection</xsl:when>
~~~~~

**Comment by jamescummings** [comment]
This breakage can't be because of _this_ commit. If we look at the parsed console output we see a lot of differences between test.rng and expected-results/test.rng

 http://jenkins.tei-c.org/job/Stylesheets/8/parsed_console/

We get things like:

````
96c206
<             <data type="anyURI"/>
---
>             <ref name="data.pointer"/>
````
and many more.... all of which have to do with datatypes and content models... I'm wondering if this has anything to do with changes to finish Pure ODD? tagging @lb42 and @hcayless since I think they may have done XSL fixes for Pure ODD datatypes/content models ... I guess the real question is whether this is all fixed in dev?  If so then should we be pushing this commit to dev instead (with @martindholmes's correction to depth=3)?

**Comment by hcayless** [comment]
Wouldn't the old stylesheets be grabbing a new p5subset.xml? That would definitely break everything.

**Comment by hcayless** [comment]
Think this was dealt with during the last release

**Comment by martindholmes** [comment]
The master branch has this fix. I'm going to add my fix to the `@depth` attribute in dev now the release is done.
