### ISSUE TITLE
CSS file is mysteriously missing from build results

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#200]
Note the tei_msdescription.css file here:

http://teijenkins.hcmc.uvic.ca/job/Stylesheets-dev/lastSuccessfulBuild/artifact/

which is missing. We need to investigate whether it's needed, and if so where it went; or whether we can remove it from the items to be archived after a build.

**Comment by martindholmes** [comment]
Council in Tokyo: MH should investigate why Jenkins thinks it should be archiving this particular file, and whether required CSS files are all in the created archive or not.

**Comment by peterstadler** [comment]
when running `make dist`, several files are created in the root(!) directory of the Stylesheets repo. On my local machine it looks like:

```
–
lrwxr-xr-x    1 pstadler  staff    17B  8 Sep 23:53 tei-print.css -> css/tei-print.css
-rw-r--r--    1 pstadler  staff   3,6M  8 Sep 23:54 tei-xsl-7.46.0a.zip
lrwxr-xr-x    1 pstadler  staff    11B  8 Sep 23:53 tei.css -> css/tei.css
lrwxr-xr-x    1 pstadler  staff    25B  8 Sep 23:53 tei_msdescription.css -> css/tei_msdescription.css
lrwxr-xr-x    1 pstadler  staff    17B  8 Sep 23:53 teislides.css -> css/teislides.css
…
```

Now, the Jenkins job configuration says to keep
"*.zip,tei*_*,debian-tei-xsl/debian/tei-xsl/usr/share/xml/tei/stylesheet/teioo.jar,dist/xml/tei/stylesheet/**/*,dist/doc/tei-xsl/**/*"; the second entry "tei*_*" seems to be the relevant one since it matches "tei_msdescription.css" but not the other files.

I think that entry should only match the deb packages (e.g. "tei-xsl_7.46.0a_all.deb") so changing the entry to "tei-xsl_*" should get rid of the css file but keep the deb files.

**Comment by martindholmes** [comment]
Building now to  see if that works. If it does, I'll fix the Jenkins repo job configs. Thanks @peterstadler!

**Comment by peterstadler** [comment]
works on my Jenkins, see https://jenkins-paderborn.tei-c.org/view/TEI%20dev/job/Stylesheets-dev/lastSuccessfulBuild/artifact/

I already fixed the job configs in https://github.com/TEIC/Jenkins/commit/31ea1fbf717c48b9165597f7552489300ec89dae so I'm closing here.
