### ISSUE TITLE
textNode not showing up in Guidelines rendering of datatype

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#236]
If you look at `@match` here:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.scoping.html

you'll see that there's no info on the datatype. The datatype is this:

~~~~~
<datatype><textNode/></datatype>
~~~~~

**Comment by lb42** [comment]
At first glance this looks like fallout from a bug in the datatype
purification process, though it's also possible that it's a
self-inflicted wound since the content model of datatype does permit
it.

There are three cases in the Glines of an attribute whose datatype
specifies just textNode instead of using either a dataRef or a
valList.

For consistency, and on the assumption that the mistake was in my
script, I've made the following changes, and can still build P5 locally

att.repeatable@context : shd be dataRef to teidata.xpath

att.lexicographic@expand : shd be dataRef to  teidata.text

att.scoping@match : shd be dataRef to teidata.xpath 

This obviously doesn't affect the issue of how we want the stylesheets
to treat the (valid) case of a datatype declared as textNode, but it
makes the encoding of the Guidelines more consistent. Which seems like
a Good Thing.

**Comment by hcayless** [comment]
Why does datatype allow textNode? Maybe it's just the nomenclature that bugs me, but attributes don't actually ever have text nodes in the DOM, just string (or other data type) values.

**Comment by lb42** [comment]
No idea. I didnt put it there guv.

**Comment by hcayless** [comment]
I'm afraid you did: https://github.com/TEIC/TEI/commit/9412441087ccec209d09b48c9ea5f9bc0c25cdb4

I can guess what you might have been thinking with it—that a text node is just a string, so it's is an acceptable value for datatype, but given that textNode is actually defined as a text node, presumably like in the XML DOM, that was probably a mistake. Since it's a fairly recent mistake though, maybe we can swiftly fix it though...That would mean this is not a Stylesheets bug, but a TEI one.

**Comment by lb42** [comment]
Looks like a fair cop. What cani have been drinking? Maybe it was a mistaken attempt to support a null value?

**Comment by martindholmes** [comment]
Problem fixed in the actual TEI source. Closing.
