### ISSUE TITLE
chaining odd forces inclusion of moduleRef, otherwise validation may fail

### ISSUE THREAD

**Issue by eduarddrenth** [TEIC/Stylesheets#271]
When chaining odd all modules have to be included in the base in spite of what http://teic.github.io/TCW/howtoChain.html describes.

See https://bitbucket.org/teibestpractices/linguistic-customization/src/091945b1c1db038155ea67fbbe669502812c0878/src/main/resources/customization/?at=master.

steps to reproduce problem:

1) compile linguistic-attributes.odd (oxygen 19 or otherwise)
2) generate xsd using tdb.odd
3) try to validate [run05.zip](https://github.com/TEIC/Stylesheets/files/1037624/run05.zip)

I have to do this

odd 1 snippet:

            <schemaSpec ident="tdb" start="TEI" source="linguistic_attributes.odd.compiled">
                <moduleRef key="tei"/>
                <moduleRef key="header"/>
                <moduleRef key="core"/>
                <moduleRef key="textstructure"/>
                <moduleRef key="linking"/>
                <moduleRef key="analysis"/>
                <moduleRef key="dictionaries"/>

odd 2 snippet:

            <schemaSpec ident="linguistics" start="TEI">
                <moduleRef key="tei"/>
                <moduleRef key="header"/>
                <moduleRef key="core"/>
                <moduleRef key="textstructure"/>
                <moduleRef key="linking"/>
                <moduleRef key="analysis"/>
                <moduleRef key="dictionaries"/>

instead of this

odd 1 snippet (only modules I need here):

            <schemaSpec ident="tdb" start="TEI" source="linguistic_attributes.odd.compiled">
                <moduleRef key="tei"/>
                <moduleRef key="header"/>
                <moduleRef key="core"/>
                <moduleRef key="textstructure"/>
                <moduleRef key="linking"/>
                <moduleRef key="analysis"/>

odd 2 snippet (the base plus dictionaries pulled in from P5):

            <schemaSpec ident="linguistics" start="TEI">
                <moduleRef key="tei"/>
                <moduleRef key="header"/>
                <moduleRef key="core"/>
                <moduleRef key="textstructure"/>
                <moduleRef key="linking"/>
                <moduleRef key="analysis"/>
                <moduleRef key="dictionaries" source="http://www.tei-c.org/release/xml/tei/odd/p5subset.xml"/>

**Comment by lb42** [comment]
What are you trying to achieve  and what is the error you have identified in the howtoChain tutorial? 

Since you generated linguistic_attributes.odd.compiled using the same (default) source as that specified for the dictionaries module in the second of your two "odd2" snippets, both versions of odd2 should have exactly the same effect.

**Comment by lb42** [comment]
I built a compiled version of your linguistic-attributes.odd, used it as source for your tdb.odd, and generated schemas from that (all in oxyGen 18).  The RELAX NG schema validated your run05 test file correctly, but the XSD schema failed with an error I do not understand. So there is something odd (ha ha) going on here, but I don't think it has anything to do with chaining.

**Comment by eduarddrenth** [comment]
Sorry, the git url I provided for the steps is not right. Using the odd's from that url will leed to success.

Use odd's from this branche:

https://bitbucket.org/teibestpractices/linguistic-customization/src/163b3bd67a02/src/main/resources/customization/?at=chaining

and then the steps from above. When validating using xsd you will see a "invalid content" fault. Also when using RNG you will see invalid content.

I never encountered non regular XSD schema or validation errors, using oxygen 19 now, 18 before.

**Comment by lb42** [comment]
This version of your linguistic-attributes.odd does not include modules namesdates and msdescription. Those modules  are therefore not available to the tdb.odd, since this  specifies the compiled version of linguistic-attributes.odd as its @source. Any  moduleRefs to other modules in tdb.odd will not have any effect unless you specify a different @source for them. The validation errors in your test file show that elements from the module namesdates (persName for example) are not available in the generated schema. You could fix this by adding  e.g. @eduarddrenth source="http://www.tei-c.org/release/xml/tei/odd/p5subset.xml" to the &lt;moduleRef key="namesdates"/> in tdb.odd 

Hope this helps.

**Comment by eduarddrenth** [comment]
But if you look here
https://bitbucket.org/teibestpractices/linguistic-customization/src/d3509735158e0c16105ba3685a9fbaee0b18947a/src/main/resources/customization/tdb.odd?at=chaining&fileviewer=file-view-default

you see I did add @source to moduleRef not present in
linguistic-attributes.odd.

**Comment by lb42** [comment]
Well, that version of tdb.odd is certainly better, but it still  produces a schema which finds your test document to be invalid. I am now seeing 5 errors about a misplaced objectDesc. 
This appears to be happening because the class model.physDescPart is not being included correctly. This  class is defined in the module tei, rather than in the module msdescription, which may well be a mistake. My hypothesis is that when your linguistic-attributes.odd is compiled the definition for that class is not being included, since you have no element which references it.  I need to do more testing to confirm this and propose a solution.

Can you confirm that this (the errors about objectDesc) is the problem you are seeing as well?

**Comment by lb42** [comment]
If I add this line 
~~~~
 <classRef key="model.physDescPart"
               source="http://www.tei-c.org/release/xml/tei/odd/p5subset.xml"/>
~~~~
to your tdb.odd and regenerate the schemas, they work correctly with your test file, which confirms my above hypothesis. I will raise an issue in the P5 tracker suggesting that  this class declaration should be moved.

**Comment by eduarddrenth** [comment]
Glad you found this problem, thanks for your effort! I Think odd chaining is a strong feature of TEI, it promotes reuse and is for me yet another reason to go for TEI when encoding corpora.
