### ISSUE TITLE
Stylesheets do not pass xml:id of floatingText to HTML5

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/Stylesheets#326]
If I write floatingText, body, head, p each with an xml:id, I get div, div, h1, p in HTML5, but the latter only with an id. To me it seems important that all identities be preserved to be possibly used as a target. It would be natural to write: for more information see… [pointing to a floatingText].

**Comment by lb42** [comment]
Out of curiosity, I tried to replicate this issue using a document contsaining this fragment:
~~~~
<body xml:id="bod">
           <div n="1" xml:id="divvy">
            <head xml:id="heady">A heading</head>
            <p xml:id="p1">Some text here.</p>
            <floatingText xml:id="floaty">
               <body>
                  <p>A life on the ocean wave</p>
               </body>
            </floatingText>
         </div>
</body>
~~~~
 Running this through the default tei to xhtml conversion, I see that the html elements corresponding with  floatingText and  body do indeed lack identifiers, while the xml:id values used  for div. head, and p are transferred to an id value on the corresponding HTML element. Actually, "body" is a special case: by default the HTML conversion gives its corresponding html:div a different identifier (TOP), presumably because this value is hardwired into other bits of the stylesheet. 

Dont forget that the TEI Stylesheets make no claim to exhaustivity, nor indeed omniscience. There are plenty of ways to customize them: see http://www.tei-c.org/release/doc/tei-xsl

**Comment by Dominique-M** [comment]
I understand that the main body may be treated differently. But if in the floatingText before the p element you add a head (“Floating life”, say) with some xml:id you will get in HTML the div n=1 heading with html:id and the floating heading without, which seams unfair to the second.

**Comment by martindholmes** [comment]
Council in Tokyo agrees that `@xml:id` values should be passed through to HTML `@id` attributes where possible, and  will make this happen for `<floatingText>`.

**Comment by sydb** [comment]
With 1ea8249f we (Stylesheets group) think we have solved this. If there are still elements with `@xml:id` in your input, @Dominique-M, which do not get `@id` in the output HTML, let us know.
Note, though, that we did this for HTML5, not plain HTML, output. (We are planning on merging the two soon, anyway.)
