### ISSUE TITLE
Test/test.odd is invalid, and worse

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#329]
@martindholmes and I (while working on Test2/) just discovered that the Test/test.odd file is invalid (due to “+” and “-” values of `@atts`). Worse, though, those values seem to be completely undocumented, but (at least partially) processed.

It appears that at least “-” is used internally (to mean “no attributes”, from an `@rend` of "noatts", which is also undocumented) in processing. See common/common_tagdocs.xsl line ~1731.

The value “+” is partially processed on line ~1105.

Council will have to decide whether we want to continue with these values or what.

**Comment by lb42** [comment]
These date back to a discussion between me and Sebastian about whether the HTML generated from a specDesc for an element should display all, or none, or just some of its associated attributes; and similarly its valLists. It's safe to say that the desired processing is currently underspecified. If you say "use @atts to determine this" then you need (I think) a convenient way of saying @atts=all of them, or maybe @atts=all the locally defined ones, or maybe you default to always doing one or the other, in which case you need a way to vary that behaviour.... it's a mess.

**Comment by martindholmes** [comment]
We were thinking that some straightforward private-uri values would work here -- something like tei:allLocal tei:allInherited tei:noLocal tei:noInherited. But the data type is name rather than URI, so maybe that's not appropriate.

Anyway, it's undocumented and half-implemented, which is a bad place for it to be. I guess the first decision would be whether it's a good idea at all; if not, then we should get rid of the lot of it, and go for a situation where you get all attributes by default, or only the ones you explicitly specify if you use `@atts`.

**Comment by sydb** [comment]
Plan: remove '-' and '+' from Test/test.odd, and add comments to common/common_tagdocs.xsl to explain that the '+' and '-' are not used and not fully supported.

IF a user thinks that specification of attrs at a greater level of abstraction is needed, a new ticket (against the TEI repo) is in order.
