### ISSUE TITLE
gap in TEI's own stylesheets which leave dictionary entries completely unformatted and solution

### ISSUE THREAD

**Issue by ghost** [TEIC/Stylesheets#342]
After days of google I found https://github.com/michmech/tei-dictionary.xsl 

somebody debug this and include to repository, license permits (see details)

**Comment by martindholmes** [comment]
Looks like a good solution to me. Perhaps we should contact the author and see if he would like to continue to migrate the stylesheets to the TEI Stylesheets repo and maintain them there.

**Comment by martindholmes** [comment]
@sydb and me: Having looked at this again, we think that the templates provided would need their @match attributes further constrained so that they don't collide with existing templates handling some of these elements in other contexts. Otherwise it looks like a good addition to the HTML templates. The other problem would be that these templates only output HTML; the Stylesheets infrastructure usually produces generic output which is later processed into specific output formats. Is it OK to have these templates, but no parallel handling for e.g. PDF output?

**Comment by HelenaSabel** [comment]
The suggested stylesheet was reviewed in today’s Stylesheets Group meeting. Although we agree that it would be an enhancement, we decided to not include it. Besides the issues already pointed out by @martindholmes in the previous comment, its integration is not compatible with current simplification efforts regarding the maintenance and development  of the TEI Stylesheets.
