### ISSUE TITLE
TEIVERSION PI uses space-separated <edition>s

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#355]
In odds/odd2odd.xsl, the routine odd2odd-getversion provides the value for the TEIVERSION PI. It simply takes all of the `<edition>` elements from the `<teiHeader>` of the source and strings them together as a long space-separated string.
1. This means p5odds.odd should require that at least one `<edition>` be present (at the moment there always is one `<edition>` in each of the main files that would be used as source, but it is not schema-enforced; and I did not check all the files that might be used as source if you were odd-chaining).
1. We should use something other than a space to separate them, perhaps " ⁋ " or some such. This is **very** low priority, as currently there are no cases of more than one `<edition>`, so it does not matter a hoot what separates them.

**Comment by sydb** [comment]
(BTW, in the rub-a-dub-dubbed version of odds/odd2odd.xsl, I have eliminated the "odd2odd-getversion" template in favor of a single `<xsl:value>` that does what it did. It also uses space to separate the string values of the `<edition>`s, as I’m trying to avoid needlessly changing what the stylesheet does.)

**Comment by martindholmes** [comment]
@sydb and @martindholmes thinking about this: Why is the PI there if the first place? Is anything done with it? Why not just output a separate PI for each `<edition>` found?

**Comment by martindholmes** [comment]
@sydb and @martindholmes investigated further, and we now see that:

The edition element being processed is the one in the p5subset.xml file, where there is only one.
The resulting processing instruction is consumed in order to create comments in output schemas.
The processing all looks under-documented and fragile but it's working fine.

We think what needs to be done is documentation at the point where the processing instruction is created, and where it is used.

**Comment by martindholmes** [comment]
@sydb and @martindholmes have added explanatory comments. Closing the ticket.
