### ISSUE TITLE
<code> in <desc> gets dropped in rng

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/Stylesheets#399]
The text gets entirely dropped, e.g.

```
<desc versionDate="2019-09-14" xml:lang="en">
    Person who is a <soCalled>source</soCalled> of information 
    (for statements such as qāla fulān b. fulān). 
    Corresponds to code <code>@SRCXX</code>.
</desc>
```

results in:

```
<a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">
    Person who is a source of information
   (for statements such as qāla fulān b. fulān). 
   Corresponds to code .
</a:documentation>
```

Note how the content of `<soCalled>` is kept (though without adding quotation marks).

**Comment by martindholmes** [comment]
I think this is handled in common/functions.xsl's tei:makeDescription() function, which has this:

~~~~~
<xsl:when test="tei:desc[@xml:lang=$firstLang]">
          <xsl:for-each select="tei:desc[@xml:lang=$firstLang]">
            <xsl:apply-templates select="." mode="inLanguage"/>
          </xsl:for-each>
        </xsl:when>
~~~~~

So the actual processing is all done in "inLanguage" mode. That brings us back to the teiodds.xsl file, where we find this:

~~~~~
  <xsl:template match="tei:desc" mode="inLanguage">
    <xsl:apply-templates/>
  </xsl:template>
~~~~~

So I think it's possible that if we just add handlers for `<tei:soCalled>` and `<tei:code>`(and anything else pertinent) to teiodds.xsl, without a mode attribute, we may solve the problem.

**Comment by sydb** [comment]
([Here](https://github.com/TEIC/Stylesheets/files/3800569/test_defaultVal_and_code_in_desc.odd.txt) is a little ODD we can use for testing this. It is the same ODD as on ticket #393. (So if you have already downloaded that one, you may not need to download this. But in either case, remember to strip the “.txt” off the end.)

**Comment by sydb** [comment]
TEI Stylesheets group tried attacking this. We changed [teiodds.xsl line 2467](https://github.com/TEIC/Stylesheets/blob/41ea4557e99b6f26f3f313789562a942d4df24de/odds/teiodds.xsl#L2467) to apply templates in mode `glossDescTitle` instead of the default mode. This has the desired effect of keeping the content of `<code>` (and also put scare quotes around `<soCalled>`), but the undesired side effect of losing the current processing of other phrase level elements like `<gi>`, which were becoming `<html:code>`.
We then reverted that change and (per @peterstadler’s suggestion) tried changing [functions.xsl line 1135](https://github.com/TEIC/Stylesheets/blob/41ea4557e99b6f26f3f313789562a942d4df24de/common/functions.xsl#L1135) to just apply templates in mode `glossDescTitle` in the first place. That had no effect at all, which initially surprised us (a lot). But @peterstadler realized that the problem was that that point in the processing is only being hit if there is an `@xml:lang` present on the `<desc>`. So we should try line 1130 instead.
Here is the [test ODD](https://github.com/TEIC/Stylesheets/files/3917354/test_defaultVal_and_code_in_desc.odd.txt) we used, a mild modification of the one above. (We added a `<desc>` that included phrase level elements for testing to the definition of `<hyphenation>`.)

**Comment by martindholmes** [comment]
@npcole, @sydb  and I figured out a fix which is coming in branch issue_399_rng_annotations...

**Comment by HelenaSabel** [comment]
Issue fixed in PR https://github.com/TEIC/Stylesheets/pull/514
