### ISSUE TITLE
Is <attRef> processed in HTML output?

### ISSUE THREAD

**Issue by martinascholger** [TEIC/Stylesheets#419]
For solving issue https://github.com/TEIC/TEI/issues/1867, the `@subtype` attribute has been added to att.textCritical via `<attRef>` which is a temporary workaround until it is possible to override the definition of `@type` with a mode=\"replace\". See issue #370. 

@sydb and I now discovered that `@subtype` is in the schema, but the HTML output of the `<lem>`, `<rdg>`, and `<rdgGrp>` specs does not list `@subtype` (e.g. https://tei-c.org/Vault/P5/3.6.0/doc/tei-p5-doc/en/html/ref-lem.html). We assume that the `<attRef>` element is not processed (accordingly)?

**Comment by raffazizzi** [comment]
It looks like [`att.textCritical`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.textCritical.html) shows membership to `att.typed`, but it is commented out in the [`classSpec`](https://github.com/TEIC/TEI/blob/dev/P5/Source/Specs/att.textCritical.xml#L24)

`@subtype` is inddeed added via `attRef`

**Comment by raffazizzi** [comment]
Update: the membership to att.typed shown on the `att.textCritical`'s [specs page](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.textCritical.html) is the one from attRef.

So the issue is that the attRef is not shown on the memeber element spec page (e.g. [`lem`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-lem.html))
