### ISSUE TITLE
html output of spec files does not show inheritance of attribute classes

### ISSUE THREAD

**Issue by martinascholger** [TEIC/Stylesheets#428]
The HTML output of attribute classes in the spec files does not show the inheritence of attribute classes. There are two parentheses at the end of a subclass, but the beginning of the second parantheses is missing. See for example: [https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-author.html](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-author.html)

**Comment by martindholmes** [comment]
@martinascholger I think the parentheses are actually matched; for example

`(att.canonical (@key, @ref))`

Two parentheses open, and two close. But the structure is puzzling. What's intended (I think) is that direct class memberships are shown without the outer parentheses, but indirect ones (those caused by membership of a class which is a member of a class) are then shown in an additional pair of parentheses after the direct membership. So we see:

`att.global (@xml:id, @n, @xml:lang, @xml:base, @xml:space) (att.global.rendition (@rend, @style, @rendition))`

meaning that the element is a member of `att.global`, providing its `@xml:*` attributes, and `att.global` is a member of `att.global.rendition`, providing three more. But the function of the additional parentheses is a bit mysterious to the reader; perhaps instead we should use an arrow?

**Comment by martinascholger** [comment]
@martindholmes how would this look like with an arrow?

**Comment by martindholmes** [comment]
I was thinking:

`att.global (@xml:id, @n, @xml:lang, @xml:base, @xml:space) => att.global.rendition (@rend, @style, @rendition)`

**Comment by lb42** [comment]
I don't think the arrow makes this clearer: au contraire. It implies that what's to the left of it is in some sort of relationship to what;s to the right of it, but that the two are separate things. Whereas the parenthetical notation makes explicit that a class is a bracketted list of items, some of which may themselves be classes, and therefore followed by a bracketted list of items. Look at a class with more than one subclass and it becomes apparent. I don't see why the parentheses are mysterious: the syntax is clear: you have a class name followed by a parenthesized list of things that constitute that class.

**Comment by martindholmes** [comment]
@lb42 You're probably right. But if bracketing were to show the inheritance, wouldn't it make more sense nested like this?

`att.global (@xml:id, @n, @xml:lang, @xml:base, @xml:space (att.global.rendition (@rend, @style, @rendition)) `

**Comment by lb42** [comment]
If att.global.rendition was a subclass of att.global yes it would. But because of the weird way we do attribute classes, it's actually the other way round: att.global is a memberOf att.global.rendition!

**Comment by sydb** [comment]
@peterstadler and I think @martinascholger’s original issue may not require any intervention, but the fact that she posted it is a reminder that the representation of attribute classes in the HTML tagdocs is confusing. Do we keep this ticket open to discuss that issue, or close it and maybe open another (now or later)?

**Comment by martinascholger** [comment]
We can close it for now and I will open a new issue the next time I am confused about the representation of attribute classes.
