### ISSUE TITLE
A jquery file with vulnerabilities

### ISSUE THREAD

**Issue by AlexJitianu** [TEIC/Stylesheets#433]
The file in question is `profiles/oepack/epub/jquery-css-transform.js` and it is covered by this vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2019-11358
There's a reference to this file within `profiles\oepack\epub\to.xsl`
It doesn't look like there is a newer jquery version that fixes it...
I'm not sure how important it is, but I would recommend to remove it so that it doesn't trigger any security scanners.

**Comment by martindholmes** [comment]
This appears in an epub profile whose only identification in its readme is "Experiments in old english teaching materials". With the exception of two upgrades to the JQuery by Peter, presumably performed in response to a similar vulnerability, t hasn't been touched since 2014, and what happened then looks to be generic stuff that was done across the repo.  @jamescummings @lb42 Do you remember what this was created for? If it has no strong use case I would suggest deleting the entire oepack folder from the repo, as soon as possible.

**Comment by sydb** [comment]
Council in general is sympathetic to the idea that we should step away from using JQuery in general, but think that for now we should look at this particular library and see if it is needed, and if so just update the JQuery.

**Comment by sydb** [comment]
Per @hcayless this has already been done (by @peterstadler), so Council thinks it should just be closed. @peterstadler to investigate.

**Comment by peterstadler** [comment]
NB: this issue is an update of #395

**Comment by peterstadler** [comment]
I will update the JQuery library to current version 3.5.1 and file a new issue for triaging all profiles to see whether we might get rid of some old stuff (especially this one).
