### ISSUE TITLE
Applying tei-to-text Transformation Using Python LXML

### ISSUE THREAD

**Issue by ylassoued** [TEIC/Stylesheets#472]
I am trying to apply the tei-to-xml XSLT to TEI documents using Python and the LXML API, but am getting the following errors. I would appreciate your help. Source code and TEI document are attached.

- Message from line 0, col 0: Invalid type
  Domain: XPATH (12)
  Type: XPATH_INVALID_TYPE (1211)
  Level: ERROR (2)
  Filename: <string>
- Message from line 137, col 0: runtime error, element 'apply-templates'
  Domain: XSLT (22)
  Type: ERR_OK (0)
  Level: ERROR (2)
  Filename: <xslt>
- Message from line 0, col 0: Failed to evaluate the 'select' expression.
  Domain: XSLT (22)
  Type: ERR_OK (0)
  Level: ERROR (2)
  Filename: <string>

[zxp.zip](https://github.com/TEIC/Stylesheets/files/5459130/zxp.zip)

**Comment by martindholmes** [comment]
@ylassoued Does LXML support XSLT 2.0 or above? I thought it was just XSLT 1.0. All our stylesheets are 2.0 (and will probably soon be 3).

**Comment by ylassoued** [comment]
Well spotted @martindholmes! LXML supports XSLT 1.0 only. :-( Thank you very much!
BTW, is it easy to convert XSLT 2.0 stylesheets into XSLT 1.0, knowing that I don't need the full TEI XSLTs, but only tei-to-text?

**Comment by martindholmes** [comment]
@ylassoued I think it would be quite difficult to convert version 2.0 stylesheets into 1.0. The first line in the tei-to-text.xsl file is:

`<xsl:import href="../common/functions.xsl"/>`

which imports a library of xsl:functions; xsl:function (user-defined function in XSLT) is not supported in XSLT 1.0. However, it doesn't look like any of those functions are actually called. But other XSLT 2 constructs are crucial; there's xsl:analyze-string and a locally-defined xsl:function, and those do most of the work. I think it might be easier just to use Saxon instead of LXML.

**Comment by ylassoued** [comment]
Thank you very much @martindholmes! This perfectly answers my question. I will then have to apply the XSLT outside of Python. I suppose I can close now the issue.
