### ISSUE TITLE
FOP binary is out of date

### ISSUE THREAD

**Issue by npcole** [TEIC/Stylesheets#497]
At time of writing, it is not possible to simply update the fop version to 2.6, because the OFFO-hyphenation project has not been updated since 2016.

Details of how to make hyphenation work are here. There appear to be three options to investigate.

https://xmlgraphics.apache.org/fop/2.6/hyphenation.html

**Comment by martindholmes** [comment]
@npcole and I think it's possible that the original OFFO-hyphenation binary for FOP 2.2 will Just Work; if so, we can just update the fop version to 2.6. Just needs a quick test, which Test2 can provide.

**Comment by martindholmes** [comment]
In commit #bd605e65 I've made the FOP version configurable from a single property, and made it 2.6 by default. This works fine with OFFO, but it turns out that MathML processing no longer works because the JEuclid plugin for FOP has not been updated. I've suppressed the single small MathML-to-PDF test we had, since it's really not a core TEI requirement to handle MathML, but I've left the test file there, and the process still downloads JEuclid in case anyone wants to override the FOP version and use an earlier one that works with JEuclid. Closing this.
