### ISSUE TITLE
Attribute `@typo` in expected-results

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#554]
In the current dev branch expected results, there is this:

https://github.com/TEIC/Stylesheets/blob/dev/Test/expected-results/test15.odd.rnc#L926

attribute typo instead of type.

This causes the test to fail on my computer, but doesn't seem to have a problem on Jenkins for some reason.

**Comment by HelenaSabel** [comment]
I’ve looked into this and the presence of `@typo` seems to be indeed the expected result in order to check the processing of `altIdent`: see [alt2.odd](https://github.com/TEIC/Stylesheets/blob/dev/Test/alt2.odd) (which is imported in [test15.odd](https://github.com/TEIC/Stylesheets/blob/dev/Test/test15.odd))
