### ISSUE TITLE
rendering of element specs in HTML documentation for customizations

### ISSUE THREAD

**Issue by kshawkin** [TEIC/Stylesheets#79]
In the HTML documentation of Tite and Lite, the element specs include the text of the `<desc>`, followed by the section number of P5 referenced by the `<ptr>`(s) that occur in `<listRef>`.  However, it does not display the `<head>` of the referenced section, nor is there a hyperlink.

**Comment by sebastianrahtz** [comment]
It's true, the default ODD to HTML does not support this. Because, I hypothesise, the processing reads, by default, p5subset.xml, which does not contain the desired info. If you switch it to read from a full copy of P5, I believe you'll see the heads. The @source attribute of schemaSpec can be used to override the default.

**Comment by kshawkin** [comment]
The HTML documentation for Lite and Tite in release has this problem.  So I guess this could be fixed either by changing the default processing that uses p5subset.xml (a fix in the stylesheets) or by overriding this in the build process (something for Council to deal with, which should be a ticket in SF).  Am I right that you think the latter is more appropriate?  If so, I'll file a bug report over there.

**Comment by sebastianrahtz** [comment]
or, thirdly,  by changing the creation of p5subset.xml to include head
elements. Unfortunately, SourceForge won't check in my changes (it seems to
be down), but that has the desired result.
`Index: Utilities/subset.xsl

===================================================================

--- Utilities/subset.xsl (revision 13106)

+++ Utilities/subset.xsl (working copy)

@@ -35,7 +35,7 @@

     <xsl:choose>

       <xsl:when test="self::div">

  <xsl:copy>

-   <xsl:copy-of select="@*"/>

+   <xsl:copy-of select="@*"/>   <xsl:copy-of select="head"/>

    <xsl:apply-templates/>

  </xsl:copy>

       </xsl:when>

@@ -49,4 +49,4 @@

   </xsl:template>
`

On 30 January 2015 at 20:57, kshawkin <notifications@github.com> wrote:

> The HTML documentation for Lite and Tite in release has this problem. So I
> guess this could be fixed either by changing the default processing that
> uses p5subset.xml (a fix in the stylesheets) or by overriding this in the
> build process (something for Council to deal with, which should be a ticket
> in SF). Am I right that you think the latter is more appropriate? If so,
> I'll file a bug report over there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/79#issuecomment-72269052>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.

**Comment by kshawkin** [comment]
Okay, looks like this has been implemented in SourceForge: https://sourceforge.net/p/tei/code/13125/ .

**Comment by PFSchaffner** [comment]
Don't know if this is a one-off, or a result of
a blunder at my end -- or a genuine glitch.

In
https://github.com/textcreationpartnership/A41403

Whereas the SGML contained two <PB tags, of which the
second was situated thus:

<DIV1 ...>
* * *
<P><PB REF="1">
<FIGURE></FIGURE>
<FIGURE></FIGURE>
</P>
<LG>
<L>Then next the ...


The XML appparently removed not only the extraneous 
containing paragraph (which is fine), but also 
the <pb tag, thus:

<div...>
* * *
<figure/>
<figure/>
<lg>
<l>Then next the ...

(The <pb tag is there now, because I manually 
added it, while making some other corrections.)

pfs


-- 
Paul Schaffner  Digital Library Production Service
PFSchaffner@umich.edu | http://www.umich.edu/~pfs/

**Comment by kshawkin** [comment]
Paul, did you post that comment to the wrong ticket?  I'm not sure how it relates to this one.

**Comment by PFSchaffner** [comment]
Thanks,

If I posted *anything* it was a mistake. I simply picked a message
from Sebastian in order to get his address into the message, 
and hit 'reply.' Presumably it had a different 'reply-to' field
which my client picked up on and sent it there instead. 

Oops?

pfs

On Tue, Feb 3, 2015, at 12:13, kshawkin wrote:
> Paul, did you post that comment to the wrong ticket?  I'm not sure how it
> relates to this one.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/TEIC/Stylesheets/issues/79#issuecomment-72691711
-- 
Paul Schaffner  Digital Library Production Service
PFSchaffner@umich.edu | http://www.umich.edu/~pfs/

**Comment by sebastianrahtz** [comment]
indeed. an oops :-}

but you have indeed hit on genuine error in tcp2tei.xsl. I fear I must now
rerun all the conversions and
compare the results to see where else this occurs.

100 million curses

Sebastuab

On 3 February 2015 at 17:27, Paul Schaffner <notifications@github.com>
wrote:

> Thanks,
>
> If I posted *anything* it was a mistake. I simply picked a message
> from Sebastian in order to get his address into the message,
> and hit 'reply.' Presumably it had a different 'reply-to' field
> which my client picked up on and sent it there instead.
>
> Oops?
>
> pfs
>
> On Tue, Feb 3, 2015, at 12:13, kshawkin wrote:
> > Paul, did you post that comment to the wrong ticket? I'm not sure how it
> > relates to this one.
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/TEIC/Stylesheets/issues/79#issuecomment-72691711
> --
> Paul Schaffner Digital Library Production Service
> PFSchaffner@umich.edu | http://www.umich.edu/~pfs/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TEIC/Stylesheets/issues/79#issuecomment-72694574>.
>



-- 

Sebastian Rahtz

Director (Research) of Academic IT

University of Oxford IT Services

13 Banbury Road, Oxford OX2 6NN. Phone +44 1865 283431


Não sou nada.

Nunca serei nada.

Não posso querer ser nada.

À parte isso, tenho em mim todos os sonhos do mundo.
